# Generated by Django 3.2.3 on 2021-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
