# Generated by Django 3.2.3 on 2021-07-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20210705_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='media',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='video',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workouts.training'),
        ),
        migrations.AddField(
            model_name='image',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workouts.training'),
        ),
    ]
