# Generated by Django 3.2.3 on 2021-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20210705_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, help_text='Etykieta do danego zdjecia', max_length=100, null=True, verbose_name='Etykieta zdjecia'),
        ),
        migrations.AddField(
            model_name='video',
            name='label',
            field=models.CharField(blank=True, help_text='Etykieta do danego filmu', max_length=100, null=True, verbose_name='Etykieta filmu'),
        ),
    ]
