# Generated by Django 3.2.3 on 2021-07-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0006_auto_20210707_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(blank=True, help_text='Krótki opis danego treningu', max_length=1000, verbose_name='Krótki opis treningu'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating of a training', null=True, verbose_name='Rating')),
                ('rating_training', models.ForeignKey(help_text='Training model that is rated by a user', on_delete=django.db.models.deletion.CASCADE, related_name='training_rating', to='workouts.training', verbose_name='Training')),
                ('rating_user', models.ForeignKey(help_text='User that rated a car', on_delete=django.db.models.deletion.CASCADE, related_name='training_rating', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Training rating',
                'verbose_name_plural': 'Training ratings',
                'unique_together': {('rating_user', 'rating_training')},
            },
        ),
    ]
