# Generated by Django 3.2.3 on 2021-07-14 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0007_auto_20210714_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_training',
            field=models.ForeignKey(blank=True, help_text='Training model that is rated by a user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_rating', to='workouts.training', verbose_name='Training'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_user',
            field=models.ForeignKey(blank=True, help_text='User that rated a car', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_rating', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
