# Generated by Django 3.2.3 on 2021-07-14 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0008_auto_20210714_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_training',
            new_name='training',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rating_user', 'training')},
        ),
    ]
